{{- if .Values.service.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ortelius-docs.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- range $key, $val := .Values.keptnLabels }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
spec:
  endpoints:
  - interval: 30s
    port: http-metrics
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ include "ortelius-docs.name" . }}
{{- end -}}