name: Close issues related to a merged pull request based on master branch.

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - master

jobs:
  closeIssueOnPrMergeTrigger:

    runs-on: ubuntu-20.04

    steps:
      - name: Closes issues related to a merged pull request.
        uses: ldez/gha-mjolnir@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
